### ISSUE TITLE
Improve MultiAnswer setMessage() and feedback display

### ISSUE THREAD

**Issue by taniwallach** [openwebwork/pg#528]
@drgrice1  wrote

> The approach that I use will work the same both with and without this pull request. I don't use the setMessage method, and instead store my messages in a custom key of the answer hash, and then deal with putting those messages into the ans_message variable in a post filter. 

That makes more work for the programmer, and others will not know how to do it.

> Part of the reason that I do this is because I don't like the table that the parserMultiAnswer.pl macro creates. It is ugly for one thing. That could be cleaned up with some work on css styling. 

So let's improve it so others can use the main `parserMultiAnswer.pl` without needing to know about special post filters. 

> Furthermore, the "In answer $i" part is generally not as informative as to how the answers match up to which parts as intended in these single result problems. Particularly when errors really relate to multiple parts and how they fit together.

I agree, and in some problems I have put in text explaining about such matters. Maybe we want to be able to have "rows" not linked to a specific box.

_Originally posted by @taniwallach in https://github.com/openwebwork/pg/issues/524#issuecomment-780594047_

**Comment by taniwallach** [comment]
@dpvc replied there:

> The styling was based on the classes at the time MultiAnswer was first developed (ages ago), and doesn't work so well now. More flexibility in the format of the message would be useful.
> 
> This was developed pretty early on, and its various uses and needs were not yet clear at the time. Some updates are probably in order.

**Comment by Alex-Jordan** [comment]
@drgrice1 Is this moot/addressed now?

**Comment by drgrice1** [comment]
Unfortunately no.  Even with the new feedback this is still an issue.  The problem is that MultiAnswer adds the `In answer $i` which is frequently not really informative.  For example, say you are using a MultiAnswer and placing the answer parts into an integral with the upper and lower limit each an answer rule, and the integrand another.  Which one is answer 1, 2, or 3?  There are more extreme cases than this though.  Generally, when singleResult is used, the order of the answers can be quite unclear in many cases.

**Comment by drgrice1** [comment]
A related issue is the deprecated table attributes used for the `error_message` table (`border`, `cellspacing`, `cellpadding`, `valign`, and `nowrap`).

**Comment by drgrice1** [comment]
And `height` on the `td`.

**Comment by drgrice1** [comment]
Probably even better is to add a new method for setting an answer message that is not tied to the answer rule order.  Then existing problems that use the `setMessage` method will still work as before, but problems can use the new method to add a message that the `In answer $i` prefix is not attached to.
